debugging

diff --git a/api/characteristics b/api/characteristics
--- a/api/characteristics
+++ b/api/characteristics
@@ -30,8 +30,11 @@ fi
 
 has_errors="$(echo "$characteristics" | jq -r 'select(.status // 0 != 0) | .status')"
 if [ "$has_errors" != "" ]; then
-    logger_error "There were errors: $characteristics"
-    content="$(echo "$characteristics" | jq -sc '{ characteristics: map(.status = (if .value then 0 else .status end)) }')"
+    logger_debug "There were errors: $characteristics"
+    content="$(echo "$characteristics" | jq -sc '{ characteristics: map(.status = (if .value then 0 else .status end)) }')" || {
+        logger_error "Failed to generate response from: $characteristics"
+        cat
+    }
     dash ./util/respond.sh 207 "$content"
 elif [ "$REQUEST_METHOD" = 'GET' ]; then
     content="$(echo "$characteristics" | jq -sc '{ characteristics: . }')"
